#default: &default
#  validation_framework: :active_model #optional

development:
#  <<: *default
  validation_framework: :active_model #optional
  database: indirect_development_db
test:
#  <<: *default
  validation_framework: :active_model #optional
  database: indirect_test_db
production:
#  <<: *default
  validation_framework: :active_model #optional
  database: <%= ENV['DB_NAME'] %>
